@startuml Roomba

class Roomba 
class CleaningModes <<enumeration>>
class LEDS <<enumeration>>
class Motors <<enumeration>>
class ControlModes <<enumeration>>
class Sensors <<enumeration>>
interface UART
interface Baudrates <<enumeration class>>

Roomba <-left- CleaningModes : 1
Roomba <-up- LEDS
Roomba <-up- Motors 
Roomba <-left- ControlModes : 1
Roomba <-down- Sensors
Roomba <-up- UART : 1
Roomba <-left- Baudrates : 1


UART <-left- Baudrates : 1

class Roomba {
  - mUARTHandle : UART
  - mSongNum : int
  + Motors : enum
  + CleaningModes : enum
  + LEDS : enum
  + Baudrates
  + Sensors
  + Notes : enum
  --
  + Roomba(mUARTHandle : UART) : void
  + Rotate(angle : int) : void
  + setMotor(motor : int, velocity : int) : void
  + startCleaning(cleaningMode : cleaningModes) : void
  + setDockMode() : void
  + setControlMode(controlmode : controlModes) : void
  + setLed( led : int, brightness : int) : void
  + setBaudrate(baudrate : baudrates) : void
  + getSensorData( sensor : int) : int
  + setSongNum(songnum : int) : void
  + turnOn() : void
  + turnOff() : void
  + ~Roomba() : void
}

class LEDS {
DD
MAX
CLEAN
SPOT
STATUS
}

class Motors {
Main_Brush
Vacuum
Side_Brush
}

enum Baudrates {
baud_invalid = 0
baud_300
baud_600
baud_1200
baud_2400
baud_4800
baud_9600
baud_14400
baud_19200
baud_28800
baud_38400
baud_57600
baud_115200
}

class UART {
- mUARTsettings : struct
--
+ UART(mUARTsettings : struct)
+ changeBaud(baudrate : enum)
+ sendBytes(buffer[] : int, numOfbytes : int)
+ sendByte(byte : int)
+ readBytes(buffer[] : int, numOfbytes : int)
+ ~UART()
}

class CleaningModes {
Normal
Full
Spot
}

class ControlModes {
Passive
Safe
Full
}

class Sensors {
Bumps_wheeldrop
Wall
Cliff_Left
Cliff_Right
VirtualWall
MotorOvercurrent
DirtDetector_Left
DirtDetector_Right
RCM
Buttons
Distance
Angle
ChargingState
Voltage
Current
Temperature
Charge
Capacity
}

@enduml